[package]
name = "cellular-automaton"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"

[dev-dependencies]
criterion = "0.6.0"


[[bench]]
harness = false
name = "automaton_benchmark"