[package]
name = "cellular-automaton"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.1"

[dev-dependencies]
criterion = "0.6.0"

[profile.release]
debug = true
strip = false

[[bench]]
harness = false
name = "automaton_benchmark"